/* Generated by tools/build.js from BRAND in tools/generate-site.js — do not edit by hand. */
window.__SERIART__ = {
  "email": "alexitosivera@gmail.com",
  "whatsappNumber": "34651358822",
  "web3formsKey": ""
};
